[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-minimal-gruvbox-dark-hard+
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-minimal-gruvbox-dark-hard+
GtkTheme=oomox-minimal-gruvbox-dark-hard+
IconTheme=oomox-minimal-gruvbox-dark-hard+
MetacityTheme=oomox-minimal-gruvbox-dark-hard+
